### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by fangxiao666** [WilcoTerink/GlabTop2-py#12]
Dear author, I am sorry to bother you.
My first question is, in line 149 of the “main.py” file, should the code “if dH > 1600” be changed to “if dH > 1.6 “?
![question1](https://github.com/user-attachments/assets/ddca888d-8fd9-47dc-b8cb-43554b7bae11)

The second question is, in the “config.cfg” file, why is “hga = 0 for the adjecent cells” used instead of “hga = 15 for the marginal cells” used in the literature?
![question2](https://github.com/user-attachments/assets/0018e9a1-15fc-405d-aa8c-a8cfe12db725)

I apologize for the bad English and look forward to your reply!
Name :- Xiaonan Fang
Email  :- 20191001632@cug.edu.cn

**Comment by WilcoTerink** [comment]
The bug you identied has now been fixed.

**Comment by fangxiao666** [comment]
Thank you for your answer. Have a nice life!
Xiaonan Fang
