### ISSUE TITLE
questions glabtop2

### ISSUE THREAD

**Issue by Semyon1999** [WilcoTerink/GlabTop2-py#3]
Dear Wilco Terink,
You have made a very useful software, thank you very much!
I have a questions. 1) Can glabtop2 assign a value of 0m only for the edges of glacier polygons (QGIS) without doing this with ice divides? Otherwise the depth of the ice is greatly underestimated (photo), this greatly affects the calculation of the total volume of ice.
2) The vertical spatial resolution of digital terrain models is inferior to instrumental measurements in the field, such more accurate data is available for some glaciers. Is it possible, for example, to manually enter these values in the attribute tables of shapefiles so that glabtop2 uses them further, and where they do not exist, them uses DEM?
Sincerely yours,
Semyon
![image](https://user-images.githubusercontent.com/58704997/110850927-69303c80-82c1-11eb-9334-10f673c99093.png)
![image](https://user-images.githubusercontent.com/58704997/110850944-6fbeb400-82c1-11eb-8654-2920b088b362.png)
semyon.griga@yandex.ru

Interesting points. About point 1) You are correct, but from my point of view those glaciers should not be individual glacier polygons but one larger polygon. Why would they need to have a different Glacier ID if they are part of the same ice mass?
Point 2) I have to think about that, but yes, that should not be too difficult. On the other hand, I do not think a single measurement can be representative for the entire grid cell resolution? Unless you do multiple measurements in that grid cell area.

**Comment by muzi2021** [comment]
> Dear Wilco Terink,
> You have made a very useful software, thank you very much!
> I have a questions. 1) Can glabtop2 assign a value of 0m only for the edges of glacier polygons (QGIS) without doing this with ice divides? Otherwise the depth of the ice is greatly underestimated (photo), this greatly affects the calculation of the total volume of ice.
> 2) The vertical spatial resolution of digital terrain models is inferior to instrumental measurements in the field, such more accurate data is available for some glaciers. Is it possible, for example, to manually enter these values in the attribute tables of shapefiles so that glabtop2 uses them further, and where they do not exist, them uses DEM?
> Sincerely yours,
> Semyon
> ![image](https://user-images.githubusercontent.com/58704997/110850927-69303c80-82c1-11eb-9334-10f673c99093.png)
> ![image](https://user-images.githubusercontent.com/58704997/110850944-6fbeb400-82c1-11eb-8654-2920b088b362.png)
> [semyon.griga@yandex.ru](mailto:semyon.griga@yandex.ru)

Hello friends, I have a question about this model. How to convert the format of DEM and gridded map of glacier outlines files from Tiff to PCRaster format.
Best wishes
muzi

**Comment by Semyon1999** [comment]
if I understand correctly then we need these commands

**Comment by Semyon1999** [comment]
if I understand correctly then we need these commands                                                                                                    
gdal_translate -of PCRaster -ot Int32 -mo VS_NOMINAL gridded.tif gridded.map
gdal_translate -of PCRaster -ot Float32 -mo VS_SCALAR clipDEM.tif clipDEM.map                                                                         perhaps this video will help you     https://www.youtube.com/watch?v=14rqwp7ZqwQ&list=LL&index=9

**Comment by muzi2021** [comment]
> if I understand correctly then we need these commands
> gdal_translate -of PCRaster -ot Int32 -mo VS_NOMINAL gridded.tif gridded.map
> gdal_translate -of PCRaster -ot Float32 -mo VS_SCALAR clipDEM.tif clipDEM.map perhaps this video will help you https://www.youtube.com/watch?v=14rqwp7ZqwQ&list=LL&index=9

Thank you very much, it really helps me a lot. But I encountered some other problems，when I run the program, an error is reported: "TypeError: %d format: a number is required, not str". I have converted the attributes of GLACID field to 'integer', but the same error still occurs.
![微信图片编辑_20210326171248](https://user-images.githubusercontent.com/77234985/112609479-88e56a00-8e56-11eb-9758-3c6f18e4b611.jpg)

Try reading that .dbf file into a geopandas dataframe and print it and see how it looks like. The GLACID field should display as integers, if not, then there is still something wrong with your attributes

**Comment by WilcoTerink** [comment]
> 
> if I understand correctly then we need these commands
> gdal_translate -of PCRaster -ot Int32 -mo VS_NOMINAL gridded.tif gridded.map
> gdal_translate -of PCRaster -ot Float32 -mo VS_SCALAR clipDEM.tif clipDEM.map perhaps this video will help you https://www.youtube.com/watch?v=14rqwp7ZqwQ&list=LL&index=9

Yes, that is correct. Generally the " -ot Float32 -mo VS_SCALAR   " bit is not required.

**Comment by nova321** [comment]
Thank you for the video. I did it according to the operation in the video， but it prompted an error:"Glacier: RGI60-13.28570 is not gridded and will therefore not be processed! ". I don't know why this error occurs.

**Comment by WilcoTerink** [comment]
It looks like you have used the wrong field for GLACID. Have a look at the file attached. I think you have used the RGIId column. the GLACID column should have integers ranging from 1 to the number of unique glaciers found in your area.

![2021-03-28 21_07_27-Window](https://user-images.githubusercontent.com/12557062/112746157-b1619580-9009-11eb-941a-3ddfb7e16aa1.png)
