### ISSUE TITLE
questions glabtop2?

### ISSUE THREAD

**Issue by muzi2021** [WilcoTerink/GlabTop2-py#5]
When I ran the model, the following error occurred. I used to run normally.
![1](https://user-images.githubusercontent.com/77234985/122238767-fa333700-cef2-11eb-8e30-19cf9c073ff6.JPG)

**Comment by WilcoTerink** [comment]
Hard to tell based on the error itself. It is important to have the DEM and GlacID maps in the same resolution, extent, and projection. Also, glacID should be a nominal map. But not sure whether this fixes the problem.

**Comment by varunkhajuria10** [comment]
Dear Wilco,
I am not able to run it via anaconda I have created the environment and downloade
![Screenshot (58)](https://user-images.githubusercontent.com/92246757/157013813-328e16fc-5406-40a7-b4e0-f7b4ebb841d9.png)
d all packages in it when i use the command python -m GlabTop2.main -i C:\my_folder\config.cfg. It is howing error ss attached

**Comment by ghost** [comment]
> When I ran the model, the following error occurred. I used to run normally. ![1](https://user-images.githubusercontent.com/77234985/122238767-fa333700-cef2-11eb-8e30-19cf9c073ff6.JPG)

Hi, have you figured it out? I also encountered that error.

**Comment by WilcoTerink** [comment]
This often happens when layers are not correctly aligned or that a glacier ID in the RGI database cannot be found in the glacID map or the other way around.

**Comment by LahaSourav** [comment]
I am trying to run your model GlabTop2-py for a single glacier. 
While running the model I am getting some errors that I am not able to fix. It would be great if you can help me to run the model successfully.
Here is the screenshot of the error.
![261465](https://user-images.githubusercontent.com/52277899/175014819-5d47f46e-2e5a-4f2b-9bc3-7d709cc8e74c.png)

It would be great if you can resolve my issue.
Looking forward to your reply.

If you need then I can share input files for checking.

**Comment by WilcoTerink** [comment]
Have you checked if there is also one glacier in the *.dbf file and one glacier id in the glacID.map? 

Also, the spatial resolution and extent of the dem and glacid maps should match.

**Comment by LahaSourav** [comment]
Thank you for your kind reply. 

The spatial resolution of and extent of dem and glacid map are the same. 
There is only one glacier in *.dbf file and glacID.map  ....I am attaching the  both the file. 
It would be great if you can quickly look at those. 
[glacid25m.zip](https://github.com/WilcoTerink/GlabTop2-py/files/8963379/glacid25m.zip)

**Comment by WilcoTerink** [comment]
The file is incomplete. There is no dem.map in it. Is that maybe also the reason why your script does not run?

**Comment by LahaSourav** [comment]
Thank you for your reply.

Sorry, I forgot to put dem.map in the .zip file. Here I am putting three input files. 
 It would be great if you can quickly look at those.
[input_files.zip.zip](https://github.com/WilcoTerink/GlabTop2-py/files/8988533/input_files.zip.zip)

**Comment by WilcoTerink** [comment]
Few things I've noticed:
1) Your DEM only has values on the location where your glacier is True. Make sure the entire map has values for the dem. Also, I see that your glacier touches the borders of the map. It's wise to choose a buffer around it, so that it can find DEM values on the cells just outside of the glacier.
2) Your GlacID map is a scalar map, while it should be a nominal map.
3) Change the glacier ID in both your dbf and placid map to a value of 1.

**Comment by LahaSourav** [comment]
Thank you so much for your time. 
Now I can successfully run the model. 
Here is the screenshot of the first successful run. 
![image](https://user-images.githubusercontent.com/52277899/175902469-ea942663-95d8-4b8f-a057-08503c7d25a7.png)

Only one thing ...all the places on the glaciers shows almost uniform ice thickness. 
Could you let me know which parameter to look at to tune the ice thickness ?

It would be great if you help me regarding the above. 

sourav
