### ISSUE TITLE
warning of runtime

### ISSUE THREAD

**Issue by ghost** [WilcoTerink/GlabTop2-py#7]

**Comment by douxy1994** [comment]
Here I adjusted my dem, but it also does not work well, could you please help me to solve this? I attached my original files in here: https://drive.google.com/file/d/18oAhI58Robd2ifm4UYBpXOjHehof6uAj/view?usp=sharing .
![image](https://user-images.githubusercontent.com/58248905/180975094-f11e6882-ceb1-4f38-8157-32c050d237f2.png)
